"""empty message

Revision ID: 581541434af1
Revises: f7b1874833d3
Create Date: 2023-12-06 17:17:02.394452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581541434af1'
down_revision = 'f7b1874833d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
